#! /bin/sh

case "$1" in
start)
    echo "Loading scull module..."
    /usr/bin/scull_load

    echo "Loading faulty module..."
    /usr/bin/module_load
    
    echo "Loading hello world module ..."
    modprobe hello
    ;;
   
  stop)
    echo "Unloading faulty module..."
    /usr/bin/module_unload

    echo "Unloading scull module..."
    /usr/bin/scull_unload
    
    echo "Unloading hello module..."
    rmmod hello
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
